config/routes.rb
Todo::Application.routes.draw do
  root to: "lists#home"
  resources :lists 
  resources :tasks
end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :name
  has_many :tasks

end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :state, :task, :list_id 
  belongs_to :list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

	respond_to :html, :json, :xml

	def home

		@lists = List.all
		@tasks = Task.all

	end

	def new

		@list = List.new

	end 

	def edit
		#change name 
		
		# render "/lists/#{@task.list_id}"
	end

	def create

		@list = List.new(params[:list])

		flash[:success] = "LIST SAVED!!!" if @list.save

		respond_with(@list)

	end 

	def show

		@tasks = Task.find_all_by_list_id(params[:id])
		@list = List.find(params[:id])

		respond_with({list: @list, tasks: @tasks})

	end

	def destroy

		@list = List.find(params[:id])

		flash[:success] = "LIST DELETED!!!" if @list.destroy 

		respond_with(@list, :location => root_path)

	end 
end 

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

	respond_to :html, :json, :xml

	def show
	end 

	def new

		@task = Task.new
		@list_id = params[:list_id ]

	end

	def create
		
		@task = Task.new(params[:task])

		@list = List.find(@task.list_id)

		flash[:success] = "TASK ADDED!!!" if @task.save
			
		respond_with(@task, :location => list_path(@task.list_id))

	end 

	def edit
	end

	def update

		@task = Task.find(params[:id])

		@task.state = true

		@list = List.find(@task.list_id)

		flash[:success] = "TASK COMPLETED!!!" if @task.save
			
		respond_with(@task, :location => list_path(@task.list_id))	

	end 

end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to "Home", root_path %>
<%= yield %>

</body>
</html>

app/views/lists/home.html.erb
<h1>LIST OF LISTS</h1>
<div>
	<ul>
		<% for list in @lists do %>
			<%= link_to list.name, "/lists/#{list.id}" %> 
			<br>
		<% end %> 
	</ul>
</div> 
<div>
	<%= link_to "Add List", new_list_path %>
</div>

app/views/lists/new.html.erb
<h1>ADD LIST!!!</h1>
<div>
	<%= form_for(@list) do |f| %>
		<p>
			<%= f.label :name %>
			<%= f.text_field :name %>
		</p>
		<p>
			<%= f.submit %>
		</p>
	<% end %>
</div>

app/views/lists/show.html.erb
<h1><%= @list.name%></h1>
<%= button_to "Delete List", {:controller => :lists, 
										:action => 'destroy',
										:id => @list.id}, :method => :delete %>
<br>
<div>
	<ul>
	<% @tasks.each do |task| %>
		<li>
			<%= task.task %>
			<% if task.state == false %>
				<%= button_to "Completed", {:controller => :tasks, 
														:action => 'update',
														:id => task.id}, :method => :put %>
			<% else %> 
				<p>COMPLETED!!!</p>
			<% end %>
		</li>
	<% end %>
	</ul>
</div>
<br> 
	<%= link_to "Add Task", new_task_path( list_id: @list.id) %> 
</br>

app/views/tasks/new.html.erb
<h1>ADD TASK!!!</h1>
<div>
	<%= form_for(@task) do |f| %>
		<p>
			<%= f.label :task %>
			<%= f.text_field :task %>
		</p>
			<%= f.hidden_field :list_id, value: @list_id %>
		<p>
			<%= f.submit %>
		</p>
	<% end %>
</div>